name: ml-predictive-maintenance
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy::numpy
  - pandas::pandas
  - scikit-learn::scikit-learn
  - matplotlib::matplotlib
  - seaborn::seaborn
  - scipy::scipy
  - pip:
    - xgboost==2.0.3
    - lightgbm==4.1.1
    - joblib==1.3.2
    - wandb==0.16.1
